spring.application.name=backend
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/banc
spring.datasource.username=postgres
spring.datasource.password=2003
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/email_verification
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Mail settings (replace with your mail server details)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=queenbeesinthewild@gmail.com
spring.mail.password=zfuw tklg glgv kzdo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Hibernate settings permet de gérer les relations entre les entités
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update