spring.application.name=backend
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/banc
spring.datasource.username=postgres
spring.datasource.password=2003
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


logging.level.org.springframework.security=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=queenbeesinthewild@gmail.com
spring.mail.password=zfuw tklg glgv kzdo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.redis.host=localhost
spring.redis.port=6379