spring.application.name=backend
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/banc
spring.datasource.username=postgres
spring.datasource.password=2003
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
